defaults:
  - clip_default
  - _self_

exp_name: clip_dictmoe

init_lambda: 0.3

model: ViT-L-14

tta: true
evaluate: false

batch_size: 16
tta_batch_size: 1
accumulate_grad_batches: 16
eval_batch_size: 16

num_devices: 1
router_hidden_layers: 2
DictMoe_layer: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]